services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mdip_smart_asset/les_troyens
    network_mode: host
    volumes:
      - ./data:/app/data
    ports:
      - "3690:3690"
