version: "3"
services:

  keymaster-account1:
    build:
      context: ../..
      dockerfile: Dockerfile.keymaster
    image: keychainmdip/keymaster
    environment:
      - KC_GATEKEEPER_URL=http://172.17.0.1
      - KC_GATEKEEPER_PORT=4224
      - KC_KEYMASTER_PORT=${KC_KEYMASTER_PORT}
    volumes:
      - ./data:/app/data
    ports:
      - ${KC_KEYMASTER_PORT}:${KC_KEYMASTER_PORT}

